name: Deploy to WP Engine
env:
  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
  WPE_INSTALL_NAME: crayfieldsstg
  THEME_NAME: test-theme
on:
  push:
    branches:
      - main

jobs:
  js-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the git repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.1

    - name: Install js/css dependencies
      uses: borales/actions-yarn@v4
      with:
        dir: wp-content/themes/${{ env.THEME_NAME }}
        cmd: install

    - name: Build js/css
      uses: borales/actions-yarn@v4
      with:
        dir: wp-content/themes/${{ env.THEME_NAME }}
        cmd: build

    - name: Clean up node modules (not needed to deploy)
      run: rm -rf wp-content/themes/${{ env.THEME_NAME }}/node_modules

    - name: Deploy to WPE
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        SCRIPT: post-deploy.sh
        WPE_ENV: ${{ env.WPE_INSTALL_NAME }}

  php-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the git repo
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Check PHP version
      run: php -v

    - name: Run composer install in theme directory
      run: cd wp-content/themes/${{ env.THEME_NAME }} && composer install && cd -

    - name: Install Acorn
      run: cd wp-content/themes/${{ env.THEME_NAME }} && composer require roots/acorn

    - name: Set up SSH
      run: |
        echo "$WPE_SSHG_KEY_PRIVATE" > /tmp/wpengine_key
        chmod 600 /tmp/wpengine_key
        mkdir -p ~/.ssh
        echo "Host crayfieldsstg.ssh.wpengine.net" > ~/.ssh/config
        echo "  User crayfieldsstg" >> ~/.ssh/config
        echo "  IdentityFile /tmp/wpengine_key" >> ~/.ssh/config
        echo "  IdentitiesOnly yes" >> ~/.ssh/config

    - name: Deploy to wpengine.com
      env:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
      run: |
        eval $(ssh-agent -s)
        ssh-add /tmp/wpengine_key
        git remote add production ssh://wpe_gha+${{ env.WPE_INSTALL_NAME }}@${{ env.WPE_INSTALL_NAME }}.ssh.wpengine.net:2222/site
        git push production main
        ssh-add -d /tmp/wpengine_key
        rm /tmp/wpengine_key

    - name: Run Sage Build Commands
      run: |
        echo "$WPE_SSHG_KEY_PRIVATE" > /tmp/wpengine_key
        chmod 600 /tmp/wpengine_key
        eval $(ssh-agent -s)
        ssh-add /tmp/wpengine_key
        ssh -o IdentitiesOnly=yes -i /tmp/wpengine_key crayfieldsstg@crayfieldsstg.ssh.wpengine.net "cd wp-content/themes/${{ env.THEME_NAME }} && ./vendor/bin/acorn migrate"
        ssh-add -d /tmp/wpengine_key
        rm /tmp/wpengine_key
